name: Open Devin Test

on:
  workflow_dispatch: # Allows manual trigger of the workflow

env:
  REGISTRY_LOGIN_SERVER: ghostregistry${{ secrets.REGISTRY_NAME_SUFFIX }}.azurecr.io # Modify this to match your actual ACR login server name

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start Devin
        run: |
          docker run -it \
              --pull=always \
              -e SANDBOX_USER_ID=$(id -u) \
              -e PERSIST_SANDBOX="true" \
              -e SSH_PASSWORD=$SSH_PASSWORD \
              -e WORKSPACE_MOUNT_PATH=${WORKSPACE_BASE:-/default/workspace/path} \
              -v ${WORKSPACE_BASE:-/default/workspace/path}:/actions-runner \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -p 3000:3000 \
              --add-host host.docker.internal:host-gateway \
              --name opendevin-app-$(date +%Y%m%d%H%M%S) \
              ghcr.io/opendevin/opendevin:0.6