name: Open Devin Test

on:
  workflow_dispatch: # Allows manual trigger of the workflow

env:
  REGISTRY_LOGIN_SERVER: ghostregistry${{ secrets.REGISTRY_NAME_SUFFIX }}.azurecr.io # Modify this to match your actual ACR login server name

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Executable Permissions for Devin's Script
        run: chmod +x runDevin.sh

      - name: Start Devin
        run: ./runDevin.sh
